name: Actualizar Firebase Rapido
on:
  push:
    paths:
      - "**.json"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: 'Auth'
        uses: 'google-github-actions/auth@v2'
        id: 'auth'
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          token_format: 'access_token'

      - name: 'Push a Firebase'
        run: |
          # 1. Identificar el archivo JSON que subió la app
          FILENAME=$(git diff --name-only HEAD^ HEAD | grep ".json" | grep -v ".github" | head -n 1)
          NEW_URL="https://raw.githubusercontent.com/${{ github.repository }}/main/$FILENAME"
          PROJECT_ID=$(echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' | jq -r .project_id)
          
          # 2. Descargar la configuración actual
          curl -X GET "https://firebaseremoteconfig.googleapis.com/v1/projects/$PROJECT_ID/remoteConfig" \
            -H "Authorization: Bearer ${{ steps.auth.outputs.access_token }}" -o config.json
          
          # 3. Inyectar la nueva URL
          jq --arg url "$NEW_URL" '.parameters.URL_NEW_UPDATE.defaultValue.value = $url' config.json > updated.json
          
          # 4. Subir a Firebase
          curl -X PUT "https://firebaseremoteconfig.googleapis.com/v1/projects/$PROJECT_ID/remoteConfig" \
            -H "Authorization: Bearer ${{ steps.auth.outputs.access_token }}" \
            -H "Content-Type: application/json" \
            -H "If-Match: *" -d @updated.json
